<form class="form-horizontal" method="POST" novalidate="novalidate">
    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-firstname">First name</label>
        <div class="controls">
            <div class="input-append">
                <input type="text"
                       placeholder="eg. Jasper"
                       class="span3"
                       name="firstname"
                       required="required"
                       value="<?=$this->firstname?>"
                       id="<?=$this->randomID?>-firstname"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['firstname']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['firstname']?>
                </span>
            </span>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-lastnameprefix">Last name prefix</label>
        <div class="controls">
            <div class="input-append">
                <input type="text"
                       class="span3"
                       placeholder="eg. van, der, etc..."
                       name="lastnameprefix"
                       value="<?=$this->lastnameprefix?>"
                       id="<?=$this->randomID?>-lastnameprefix"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['lastnameprefix']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['lastnameprefix']?>
                </span>
            </span>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-lastname">Lastname</label>
        <div class="controls">
            <div class="input-append">
                <input type="text"
                       class="span3"
                       placeholder="eg. Stafleu"
                       name="lastname"
                       required="required"
                       value="<?=$this->lastname?>"
                       id="<?=$this->randomID?>-lastname"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['lastname']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['lastname']?>
                </span>
            </span>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-email">Email adress</label>
        <div class="controls">
            <div class="input-append">
                <input type="email"
                       class="span3"
                       placeholder="eg. j.stafleu@jcgroep.nl"
                       name="email"
                       required="required"
                       pattern=".+@.+\..+"
                       value="<?=$this->email?>"
                       id="<?=$this->randomID?>-email"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['email']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['email']?>
                </span>
            </span>
            <?php } ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-email-repeat">Repeat email adres</label>
        <div class="controls">
            <div class="input-append">
                <input type="email"
                       class="span3"
                       placeholder="same as above"
                       name="email-repeat"
                       required="required"
                       pattern=".+@.+\..+"
                       id="<?=$this->randomID?>-email-repeat"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['email-repeat']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['email-repeat']?>
                </span>
            </span>
            <?php } ?>
            <span class="help-block">
                Please repeat your email adress to ensure it is correct. We ask
                you to do this because we sent password reset requests to this
                email adress, and we need to ensure you entered it correctly.
            </span>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="<?=$this->randomID?>-pass">Password</label>
        <div class="controls">
            <div class="input-append">
                <input type="password"
                       class="span3"
                       placeholder="pick any, at least 10 characters long"
                       name="pass"
                       required="required"
                       pattern=".{10,}"
                       id="<?=$this->randomID?>-pass"
                />
                <span class="add-on">
                    <i class="icon-edit" title="Required"></i>
                    <i class="icon-check" title="Accepted"></i>
                </span>
            </div>
            <?php if ( !empty($this->errors['pass']) ) {?>
            <span class="help-inline">
                <span class="alert alert-error span3">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Error</strong>: <?=$this->errors['pass']?>
                </span>
            </span>
            <?php } ?>
        </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary" name="submit" value="create">Save user</button>
        <button type="reset" class="btn">Reset form</button>
    </div>

</form>