<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Login</title>

<base href="/ums/"/>

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" />
<link href="styles/main.css" rel="stylesheet" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

</head>
<body>
    <header class="jumbotron subhead">
        <div class="container">
            <h1>UMS</h1>
            <p class="lead">
                A <u>U</u>ser <u>M</u>anagement <u>S</u>ystem designed to be
                distributable as code examples of my coding style.<br/>
                This version was created fully from scratch.
            </p>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <article class="span9">
                <?=new UMS\Views\Content('userform.phtml', $this)?>
            </article>
            <aside class="span3">
                <?=new UMS\Views\Login('login-box.phtml')?>
            </aside>
        </div>
    </div>
</body>
</html>